from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.domain.entities.chunk import Chunk


class ChunkRepository(Protocol):
    async def add_many(self, chunks: Sequence[Chunk]) -> None: ...
    async def get_by_id(self, chunk_id: UUID) -> Chunk | None: ...
    async def get_by_ids(self, chunk_ids: Sequence[UUID]) -> list[Chunk]: ...
    async def list_by_file(self, file_id: UUID) -> list[Chunk]: ...
    async def deactivate_by_file(self, file_id: UUID) -> None: ...
    async def delete_by_file(self, file_id: UUID) -> None: ...
    async def delete_by_repository(self, repository_id: UUID) -> None: ...
