from typing import Protocol
from uuid import UUID

from app.domain.entities.conversation import Conversation


class ConversationRepository(Protocol):
    async def add(self, conversation: Conversation) -> Conversation: ...
    async def get_by_id(self, conversation_id: UUID) -> Conversation | None: ...
    async def list_for_user(
        self, user_id: UUID, workspace_id: UUID | None, limit: int, offset: int
    ) -> list[Conversation]: ...
    async def update_summary(self, conversation_id: UUID, summary: str) -> None: ...
    async def increment_turn_count(self, conversation_id: UUID) -> int: ...
    async def soft_delete(self, conversation_id: UUID) -> None: ...
