from typing import Protocol
from uuid import UUID

from app.domain.entities.file import File


class FileRepository(Protocol):
    async def add(self, file: File) -> File: ...
    async def get_by_id(self, file_id: UUID) -> File | None: ...
    async def get_by_repository_and_path(self, repository_id: UUID, path: str) -> File | None: ...
    async def list_by_repository(self, repository_id: UUID) -> list[File]: ...
    async def upsert(self, file: File) -> File: ...
