from typing import Protocol
from uuid import UUID

from app.domain.entities.indexing_job import IndexingJob


class IndexingJobRepository(Protocol):
    async def add(self, job: IndexingJob) -> IndexingJob: ...
    async def get_by_id(self, job_id: UUID) -> IndexingJob | None: ...
    async def list_by_repository(self, repository_id: UUID) -> list[IndexingJob]: ...
    async def update(self, job: IndexingJob) -> IndexingJob: ...
