from typing import Protocol
from uuid import UUID

from app.domain.entities.workspace import Workspace


class WorkspaceRepository(Protocol):
    async def add(self, workspace: Workspace) -> Workspace: ...
    async def get_by_id(self, workspace_id: UUID) -> Workspace | None: ...
    async def list_for_owner(self, owner_id: UUID) -> list[Workspace]: ...
    async def delete(self, workspace_id: UUID) -> None: ...
